services:
  backend:
    init: true # Ensure process receives SIGTERM on stop
    build:
      context: ./backend
    ports:
      - "9000:9000"

  frontend:
    build: 
      context: ./frontend/schedulii-ui
    ports:
      - "8080:80"

  database:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    container_name: database
    restart: always
    user: postgres
    ports: 
      - "5432:5432"
    volumes:
      - ./assets/database/schema.sql:/docker-entrypoint-initdb.d/1_initdb.sql
      - ./assets/database/pre_load.sql:/docker-entrypoint-initdb.d/2_initdb.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    volumes:
      - ./assets/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - monitoring_data:/prometheus
    profiles:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    ports:
      - "3000:3000"
    profiles:
      - monitoring

volumes:
  monitoring_data:
