global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    honor_timestamps: true
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    honor_timestamps: true
    static_configs:
      - targets: ['localhost:9000']
