name: Execute Project Checks
on: pull_request

jobs:
  project:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Title
        uses: amannn/action-semantic-pull-request@v5
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
